"""Repository interfaces — services depend on these, not concrete classes."""
from typing import Protocol

from app.models.customer import Customer
from app.models.order import Order


class CustomerRepo(Protocol):
    def get(self, customer_id: int) -> Customer | None: ...
    def add(self, *, email: str, name: str) -> Customer: ...
    def list(self) -> list[Customer]: ...


class OrderRepo(Protocol):
    def add(self, order: Order) -> Order: ...
    def get(self, order_id: int) -> Order | None: ...
    def list_for_customer(self, customer_id: int) -> list[Order]: ...


class StockRepo(Protocol):
    def get_price(self, sku: str) -> int: ...   # cents
    def get_stock(self, sku: str) -> int: ...
    def decrement(self, sku: str, qty: int) -> None: ...
